title: onepointsixtwo blog
description: Thoughts and updates from onepointsixtwo
url: "https://blog.onepointsixtwo.com"
baseurl: ""

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
